# This is a basic workflow to help you get started with Actions

name: Get New Transcripts

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'  # every day at 00:00 UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Python dependencies
        run: pip install youtube_transcript_api yt-dlp

      # Runs a set of commands using the runners shell
      - name: Download new transcripts
        run: |
          cd Infrared
          yt-dlp --flat-playlist --print id https://youtube.com/playlist?list=PLAJIhnd1mbiD4JdPj7DndVRj3UPN8PzQZ > video_ids.txt
          python ../download_transcripts.py
      
      - name: Commit new transcripts
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update transcripts"
          git push
